# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &OrgHaushaltA
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgHaushaltAMSP

        # ID to load the MSP definition as
        ID: OrgHaushaltAMSP

        MSPDir: ../organizations/peerOrganizations/orgHaushaltA.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgHaushaltAMSP.admin', 'OrgHaushaltAMSP.peer', 'OrgHaushaltAMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgHaushaltAMSP.admin', 'OrgHaushaltAMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgHaushaltAMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgHaushaltAMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.orgHaushaltA.example.com
              Port: 11051
