# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &OrgHaushaltB
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgHaushaltBMSP

        # ID to load the MSP definition as
        ID: OrgHaushaltBMSP

        MSPDir: ../organizations/peerOrganizations/orgHaushaltB.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgHaushaltBMSP.admin', 'OrgHaushaltBMSP.peer', 'OrgHaushaltBMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgHaushaltBMSP.admin', 'OrgHaushaltBMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgHaushaltBMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgHaushaltBMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.orgHaushaltB.example.com
              Port: 11251
